version: '3.1'

services:
    api-gateway:
      build: ./api-gateway
      container_name: api-gateway
      ports:
        - "80:8090"
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false
      depends_on:
        - eureka-server
      networks:
        - sprintapp

    gestao-service:
      build: ./gestao-service
      container_name: gestao-service
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false
      depends_on:
        - eureka-server
      networks:
        - sprintapp

    eureka-server:
      build: ./eureka-server
      container_name: eureka-server
      ports:
        - "8761:8761"
      networks:
        - sprintapp
    
networks:
  sprintapp: 
    driver : bridge