version: '3.1'

services:
    api-gateway:
      image: devluis27/api-gateway:latest
      ports:
        - "8099:8099"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka-server:8761/eureka/
           -Dspring.profiles.active=prod
        - GRPC_HOST_GESTAO=gestao-service
        - GRPC_HOST_FINANCEIRO=0
        - GRPC_HOST_CORP=corporative-service
      depends_on:
        - eureka-server
      links:
        - gestao-service
        - eureka-server
      networks:
        - sprintapp

    gestao-service:
      image: devluis27/gestao-service:latest
      ports:
        - "8080:8080"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka-server:8761/eureka/
           -Dspring.profiles.active=prod
        - GRPC_HOST_CORP=corporative-service
      depends_on:
        - eureka-server
      links:
        - eureka-server
      networks:
        - sprintapp

    corporative-service:
      image: devluis27/corporative-service:latest
      ports:
        - "8081:8081"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka-server:8761/eureka/
           -Dspring.profiles.active=prod
      depends_on:
        - eureka-server
      links:
        - eureka-server
      networks:
        - sprintapp
        
    auth-service:
      image: devluis27/auth-service:latest
      ports:
        - "9001:9001"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka-server:8761/eureka/
           -Dspring.profiles.active=prod
        - IP_HOST=eureka-server
      depends_on:
        - eureka-server
      links:
        - eureka-server
      networks:
        - sprintapp      
        
    eureka-server:
      image: devluis27/eureka-server:latest
      ports:
        - "8761:8761"
      networks:
        - sprintapp
    
networks:
  sprintapp: 
    driver : bridge