version: '3.1'

services:
    api-gateway:
      image: devluis27/api-gateway:latest
      ports:
        - "8099:8099"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=eureka-server
           -Dspring.profiles.active=prod
        - IP_HOST=eureka-server
        - GRPC_HOST_GESTAO=gestao-service
        - GRPC_HOST_FINANCEIRO=financeiro-service
        - GRPC_HOST_CORP=corporative-service
      depends_on:
        - gestao-service
      links:
        - gestao-service
        - eureka-server
        - financeiro-service
      networks:
        - sprintapp

    gestao-service:
      image: devluis27/gestao-service:latest
      ports:
        - "8080:8080"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=eureka-server
           -Dspring.profiles.active=prod
        - IP_HOST=eureka-server
        - POSTGRES_URL=postgres-1.cng4etzlwfe4.us-east-1.rds.amazonaws.com/dbmicro
        - POSTGRES_USER=postgres
        - POSTGRES_PASS=rootkey2021
        - GRPC_HOST_CORP=corporative-service
      depends_on:
        - corporative-service
      links:
        - eureka-server
        - corporative-service
      networks:
        - sprintapp

    corporative-service:
      image: devluis27/corporative-service:latest
      ports:
        - "8081:8081"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=eureka-server
           -Dspring.profiles.active=prod
        - IP_HOST=eureka-server
        - POSTGRES_URL=postgres-1.cng4etzlwfe4.us-east-1.rds.amazonaws.com/dbmicro
        - POSTGRES_USER=postgres
        - POSTGRES_PASS=rootkey2021
        - GRPC_HOST_CORP=corporative-service 
      depends_on:
        - financeiro-service
      links:
        - eureka-server
      networks:
        - sprintapp

    financeiro-service:
      image: devluis27/financeiro-service:latest
      ports:
        - "8082:8082"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=eureka-server
           -Dspring.profiles.active=prod
        - IP_HOST=eureka-server
        - POSTGRES_URL=postgres-1.cng4etzlwfe4.us-east-1.rds.amazonaws.com/dbmicro
        - POSTGRES_USER=postgres
        - POSTGRES_PASS=rootkey2021
        - GRPC_HOST_CORP=corporative-service
      depends_on:
        - auth-service
      links:
        - eureka-server
      networks:
        - sprintapp
        
    auth-service:
      image: devluis27/auth-service:latest
      ports:
        - "9001:9001"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=eureka-server
           -Dspring.profiles.active=prod
        - IP_HOST=eureka-server
        - POSTGRES_URL=postgres-1.cng4etzlwfe4.us-east-1.rds.amazonaws.com/dbmicro
        - POSTGRES_USER=postgres
        - POSTGRES_PASS=rootkey2021
      depends_on:
        - eureka-server
      links:
        - eureka-server
      networks:
        - sprintapp      

    eureka-server:
      image: devluis27/eureka-server:latest   
      ports:
        - "8761:8761"
      networks:
        - sprintapp
    
networks:
  sprintapp: 
    driver : bridge