server:
  port: 8099
spring:
  application:
    name: grpc-gateway

grpc:
  client:
    gestao-service:
      address: static://${IP_HOST}:9991
      negotiationType: plaintext
    financeiro-service:
      address: static://${IP_HOST}:7575
      negotiationType: plaintext
    corporative-service:
      address: static://${IP_HOST}:9990
      negotiationType: plaintext
