server:
  port: 8099
spring:
  application:
    name: grpc-gateway

grpc:
  client:
    gestao-service:
      address: static://localhost:9991
      negotiationType: plaintext
    financeiro-service:
      address: static://localhost:7575
      negotiationType: plaintext
    corporative-service:
      address: static://localhost:9990
      negotiationType: plaintext
