version: '3'

services:    
    PostgreSQL:
      image: postgres
      container_name: PostgreSQL
      environment:
        POSTGRES_PASSWORD: "root"
      ports:
        - "15432:5432"
      volumes:
        - /home/PostgreSQL:/var/lib/postgresql/data 
      networks:
        - postgres-network
        - sprintapp   
    
    pgadmin4:
      image: dpage/pgadmin4
      container_name: pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "db@email.com"
        PGADMIN_DEFAULT_PASSWORD: "root"
      ports:
        - "16543:80"
      depends_on:
        - PostgreSQL
      networks:
        - postgres-network
        
networks:
  sprintapp: 
    driver : bridge
  postgres-network:
    driver: bridge