server:
  port: 8080
spring:
  application:
    name: gestao-service
grpc:
  server:
    port: 9991
  client:
    corporative-service:
      address: static://${GRPC_HOST_CORP}:9990
      negotiationType: plaintext
