version: '3.1'

services:
    api-gateway:
      build: ./api-gateway
      container_name: api-gateway
      mem_limit: 1024m
      ports:
        - "8090:8090"
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false


    gestao-service:
      build: ./gestao-service
      container_name: gestao-service
      mem_limit: 1024m
      ports:
        - "8080:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false
      networks:
        - sprintapp

    financeiro-service:
      build: ./financeiro-service
      container_name: financeiro-service
      mem_limit: 1024m
      ports:
        - "8082:8082"
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false
      networks:
        - sprintapp

    corporative-service:
      build: ./corporative-service
      container_name: corporative-service
      mem_limit: 1024m
      ports:
        - "8081:8081"
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false
      networks:
        - sprintapp

    eureka-server:
      build: ./eureka-server
      container_name: eureka-server
      ports:
        - "8761:8761"
      mem_limit: 1024m
      
networks:
  sprintapp: 
    driver : bridge