version: '3.1'

services:
    api-gateway:
      image: devluis27/api-gateway:latest
      ports:
        - "8099:8099"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=eureka-server
           -Dspring.profiles.active=prod
        - IP_HOST=https://ec2-3-89-85-77.compute-1.amazonaws.com/
      depends_on:
        - eureka-server
      networks:
        - sprintapp

    gestao-service:
      image: devluis27/gestao-service:latest
      ports:
        - "8080:8080"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=eureka-server
           -Dspring.profiles.active=prod
        - IP_HOST=https://ec2-3-89-85-77.compute-1.amazonaws.com/
      depends_on:
        - eureka-server
      networks:
        - sprintapp
        
    auth-service:
      image: devluis27/auth-service:latest
      ports:
        - "9001:9002"
      environment:
        - JAVA_OPTS=
           -DEUREKA_SERVER=eureka-server
           -Dspring.profiles.active=prod
        - IP_HOST=https://ec2-3-89-85-77.compute-1.amazonaws.com/
      depends_on:
        - eureka-server
      networks:
        - sprintapp      
        
    eureka-server:
      image: devluis27/eureka-server:latest
      ports:
        - "8761:8761"
      networks:
        - sprintapp
    
networks:
  sprintapp: 
    driver : bridge