version: '3.1'

services:
    api-gateway:
      build: ./api-gateway
      container_name: api-gateway
      mem_limit: 1024m
      ports:
        - "80:8090"
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false
      depends_on:
        - eureka-server
      networks:
        - sprintapp

    gestao-service:
      build: ./gestao-service
      container_name: gestao-service
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false
      depends_on:
        - eureka-server
      networks:
        - sprintapp

    financeiro-service:
      build: ./financeiro-service
      container_name: financeiro-service
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false
      depends_on:
        - eureka-server
      networks:
        - sprintapp

    corporative-service:
      build: ./corporative-service
      container_name: corporative-service
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - AUTH_ENABLED=false
      depends_on:
        - eureka-server   
      networks:
        - sprintapp

    eureka-server:
      build: ./eureka-server
      container_name: eureka-server
      ports:
        - "8761:8761"
      mem_limit: 1024m
      networks:
        - sprintapp
    
networks:
  sprintapp: 
    driver : bridge